//! Builds the cxx-qt bridges, the C++ shim and the `cc.caixa.opensesh` QML module.

use std::path::Path;

use cxx_qt_build::{CxxQtBuilder, QmlModule};

/// Icons generated by `cargo xtask icons`; every `.svg` in it is compiled into the Qt resources
/// (served as `qrc:/qt/qml/cc/caixa/opensesh/qml/icons/<name>.svg`).
const ICONS_DIR: &str = "qml/icons";

fn main() {
    println!("cargo::rerun-if-changed={ICONS_DIR}");
    let mut resources = vec!["data/icons/cc.caixa.OpenSesh.svg".to_owned()];
    resources.extend(svg_files(Path::new(ICONS_DIR)));

    let module = QmlModule::new("cc.caixa.opensesh")
        .version(1, 0)
        .qml_files(["qml/Main.qml", "qml/CrashDialog.qml"])
        // Lets qmllint / qmlls resolve the QtQuick types used by the module.
        .depend("QtQuick");

    let builder = CxxQtBuilder::new_qml_module(module)
        // Export only cpp/ as `opensesh-app/...` headers. The default (the whole crate) makes
        // cxx-qt-build watch every file in the crate, so any Rust edit would rerun moc,
        // qmlcachegen, rcc and all C++ compilation.
        .crate_include_root(Some("cpp".to_owned()))
        .files(["src/bridge/app_info.rs", "src/bridge/sesame.rs", "src/bridge/shim.rs"])
        .cpp_file("cpp/app_shim.cpp")
        // The app logo is served as qrc:/qt/qml/cc/caixa/opensesh/data/icons/cc.caixa.OpenSesh.svg
        .qrc_resources(resources)
        // Qt Qml requires Qt Network on macOS; linking it everywhere keeps the build uniform.
        .qt_module("Network");

    // qmlcachegen compiles QML bindings to C++ that embeds the UTF-8 QML strings. Without
    // `/utf-8`, MSVC reads those sources in the ANSI code page and mangles any non-ASCII text
    // ("·" became "Â·"). Qt's own CMake integration passes the same flag.
    let is_msvc = std::env::var("CARGO_CFG_TARGET_ENV").is_ok_and(|env| env == "msvc");
    // SAFETY: only adds a source-encoding flag; it doesn't change the ABI, defines or any other
    // setting cxx-qt-build relies on.
    let builder = unsafe {
        builder.cc_builder(move |cc| {
            if is_msvc {
                cc.flag("/utf-8");
            }
        })
    };
    builder.build();

    add_qt_rpath_for_private_installs();
}

/// On Linux, a Qt installed outside the dynamic loader's default directories (aqtinstall, the Qt
/// online installer, a source build in `/usr/local/Qt-x.y.z`) can't be found at run time, so
/// `cargo run` / `cargo test` would fail with "libQt6Gui.so.6: cannot open shared object file".
/// Embed an rpath to its `lib` directory in that case. Distro Qt needs nothing, and release
/// packaging (Sprint 18) rewrites the rpath anyway.
fn add_qt_rpath_for_private_installs() {
    println!("cargo::rerun-if-env-changed=QMAKE");
    let is_linux = std::env::var("CARGO_CFG_TARGET_OS").is_ok_and(|os| os == "linux");
    if !is_linux {
        return;
    }
    let Some(libs) = qmake_query("QT_INSTALL_LIBS") else {
        return;
    };
    if !is_loader_default_dir(&libs) {
        println!("cargo::rustc-link-arg=-Wl,-rpath,{libs}");
    }
}

/// Directories the Linux dynamic loader searches without configuration, including multiarch
/// subdirectories such as `/usr/lib/x86_64-linux-gnu`.
fn is_loader_default_dir(dir: &str) -> bool {
    let dir = dir.trim_end_matches('/');
    [
        "/usr/lib",
        "/usr/lib64",
        "/usr/lib32",
        "/lib",
        "/lib64",
        "/lib32",
    ]
    .iter()
    .any(|default| {
        dir == *default
            || dir.strip_prefix(default).is_some_and(|rest| {
                rest.starts_with('/')
                    && rest.ends_with("-linux-gnu")
                    && rest.matches('/').count() == 1
            })
    })
}

/// Runs `qmake -query <property>` with the same qmake lookup as cxx-qt's `qt-build-utils`:
/// the `QMAKE` environment variable first, then `qmake6` / `qmake` on `PATH`.
fn qmake_query(property: &str) -> Option<String> {
    let candidates: Vec<String> = match std::env::var("QMAKE") {
        Ok(qmake) if !qmake.is_empty() => vec![qmake],
        _ => vec!["qmake6".to_owned(), "qmake".to_owned()],
    };
    candidates.iter().find_map(|qmake| {
        let output = std::process::Command::new(qmake)
            .args(["-query", property])
            .output()
            .ok()?;
        let value = String::from_utf8(output.stdout).ok()?.trim().to_owned();
        (output.status.success() && !value.is_empty()).then_some(value)
    })
}

/// Sorted `.svg` paths (with forward slashes) directly inside `dir`; empty if it doesn't exist.
fn svg_files(dir: &Path) -> Vec<String> {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut files: Vec<String> = entries
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "svg"))
        .map(|path| path.to_string_lossy().replace('\\', "/"))
        .collect();
    files.sort();
    files
}
