//! `THIRD_PARTY_NOTICES.md`, rendered from both asset manifests (`assets/icons/icons.toml` and
//! `assets/fonts/fonts.toml`), so `cargo xtask icons` and `cargo xtask fonts` always write the
//! same complete file whichever runs last.

use std::fmt::Write as _;
use std::path::Path;

use anyhow::{Context, Result};

use crate::common::write_if_changed;
use crate::{fonts, icons};

/// Generated notices file, relative to the workspace root.
const NOTICES: &str = "THIRD_PARTY_NOTICES.md";

/// Renders the notices from the manifests in `root` and writes them if they changed.
///
/// # Errors
///
/// Fails if a manifest is missing or invalid, or the file can't be written.
pub fn write(root: &Path) -> Result<()> {
    let text = render(&icons::load_manifest(root)?, &fonts::load_manifest(root)?)?;
    write_if_changed(&root.join(NOTICES), text)?;
    println!("wrote {NOTICES}");
    Ok(())
}

fn render(icons: &icons::Manifest, fonts: &fonts::Manifest) -> Result<String> {
    let mut out = String::new();
    out.push_str("# Third-party notices\n\n");
    out.push_str(
        "<!-- Generated by `cargo xtask icons` and `cargo xtask fonts` from \
         assets/icons/icons.toml and assets/fonts/fonts.toml. Do not edit by hand. -->\n\n\
         OpenSesh is licensed under GPL-3.0-or-later (see `LICENSE`). It bundles the following \
         third-party assets, which keep their own licenses.\n\n## Icons\n\n",
    );
    for (source_id, used) in icons::used_icons(icons)? {
        let source = icons
            .sources
            .get(source_id)
            .with_context(|| format!("unknown icon source `{source_id}`"))?;
        let mut names: Vec<&str> = used.iter().map(|(_, upstream)| *upstream).collect();
        names.sort_unstable();
        names.dedup();
        let license = icons::license_copy(source_id);
        writeln!(out, "### {} {}\n", source.package, source.version)?;
        writeln!(out, "- Homepage: <{}>", source.homepage)?;
        writeln!(
            out,
            "- License: {}. Full text: [`{license}`]({license})",
            source.license
        )?;
        for file in &source.extra_notice_files {
            let copy = icons::notice_copy(source_id, file)
                .with_context(|| format!("invalid extra notice file `{file}`"))?;
            writeln!(out, "- Also read: [`{copy}`]({copy})")?;
        }
        if let Some(notice) = &source.notice {
            writeln!(out, "- Note: {}", notice.trim())?;
        }
        writeln!(
            out,
            "- Source: `https://registry.npmjs.org/{}` (tarball sha256 `{}`)",
            source.package, source.sha256
        )?;
        writeln!(out, "- Icons used: {}\n", code_list(&names))?;
    }

    out.push_str("## Fonts\n\n");
    for source in fonts.sources.values() {
        let license = format!("{}/{}", fonts::LICENSES_OUT, source.license_output);
        let files: Vec<&str> = source.files.values().map(String::as_str).collect();
        writeln!(out, "### {} {}\n", source.name, source.version)?;
        writeln!(out, "- Homepage: <{}>", source.homepage)?;
        writeln!(
            out,
            "- License: {}. Full text: [`{license}`]({license})",
            source.license
        )?;
        writeln!(
            out,
            "- Source: `{}` (sha256 `{}`)",
            source.url, source.sha256
        )?;
        writeln!(
            out,
            "- Files bundled (unmodified, in `crates/opensesh-app/fonts/`): {}\n",
            code_list(&files)
        )?;
    }
    // Exactly one trailing newline.
    let trimmed = out.trim_end().len();
    out.truncate(trimmed);
    out.push('\n');
    Ok(out)
}

fn code_list(items: &[&str]) -> String {
    items
        .iter()
        .map(|item| format!("`{item}`"))
        .collect::<Vec<_>>()
        .join(", ")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn repo_root() -> std::path::PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("..")
    }

    #[test]
    fn notices_cover_every_source_and_link_existing_licenses() {
        let root = repo_root();
        let icons = icons::load_manifest(&root).unwrap();
        let fonts = fonts::load_manifest(&root).unwrap();
        let text = render(&icons, &fonts).unwrap();
        assert!(text.contains("## Icons\n"));
        assert!(text.contains("## Fonts\n"));
        for (id, source) in &icons.sources {
            assert!(text.contains(&format!("### {} {}", source.package, source.version)));
            assert!(root.join(icons::license_copy(id)).is_file(), "{id}");
        }
        for source in fonts.sources.values() {
            assert!(text.contains(&format!("### {} {}", source.name, source.version)));
            assert!(
                root.join(fonts::LICENSES_OUT)
                    .join(&source.license_output)
                    .is_file()
            );
        }
        assert!(text.ends_with(".ttf`\n"));
    }

    /// `cargo xtask icons` / `fonts` must be re-run after editing a manifest.
    #[test]
    fn committed_notices_are_up_to_date() {
        let root = repo_root();
        let expected = render(
            &icons::load_manifest(&root).unwrap(),
            &fonts::load_manifest(&root).unwrap(),
        )
        .unwrap();
        let committed = std::fs::read_to_string(root.join(NOTICES)).unwrap();
        assert_eq!(
            committed.replace("\r\n", "\n"),
            expected,
            "THIRD_PARTY_NOTICES.md is stale: run `cargo xtask icons`"
        );
    }
}
