//! `THIRD_PARTY_NOTICES.md`, rendered from every bundle manifest (`assets/icons/icons.toml`,
//! `assets/fonts/fonts.toml`, `assets/themes/themes.toml` and `assets/conpty/conpty.toml`), so
//! `cargo xtask icons`, `fonts`, `conpty` and `notices` always write the same complete file
//! whichever runs last.

use std::fmt::Write as _;
use std::path::Path;

use anyhow::{Context, Result, ensure};
use serde::Deserialize;

use crate::common::write_if_changed;
use crate::{conpty, fonts, icons};

/// Generated notices file, relative to the workspace root.
const NOTICES: &str = "THIRD_PARTY_NOTICES.md";

/// The bundled terminal themes, relative to the workspace root.
const THEMES_DIR: &str = "assets/themes";

/// `assets/themes/themes.toml`: where the bundled terminal themes come from.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ThemesManifest {
    schema_version: i64,
    source: Vec<ThemeSource>,
}

/// One upstream repository of bundled themes.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct ThemeSource {
    name: String,
    repository: String,
    commit: String,
    license: String,
    /// Relative to `assets/themes`.
    license_files: Vec<String>,
    /// In `assets/themes/upstream`.
    files: Vec<String>,
}

/// Reads `assets/themes/themes.toml`.
///
/// # Errors
///
/// Fails if it is missing or invalid.
pub fn load_themes(root: &Path) -> Result<ThemesManifest> {
    let path = root.join(THEMES_DIR).join("themes.toml");
    let text = std::fs::read_to_string(&path)
        .with_context(|| format!("could not read {}", path.display()))?;
    let manifest: ThemesManifest =
        toml::from_str(&text).with_context(|| format!("{} is invalid", path.display()))?;
    ensure!(
        manifest.schema_version == 1,
        "{}: unsupported schema_version {}",
        path.display(),
        manifest.schema_version
    );
    Ok(manifest)
}

/// Renders the notices from the manifests in `root` and writes them if they changed.
///
/// # Errors
///
/// Fails if a manifest is missing or invalid, or the file can't be written.
pub fn write(root: &Path) -> Result<()> {
    let text = render(
        &icons::load_manifest(root)?,
        &fonts::load_manifest(root)?,
        &load_themes(root)?,
        &conpty::load_manifest(root)?,
    )?;
    write_if_changed(&root.join(NOTICES), text)?;
    println!("wrote {NOTICES}");
    Ok(())
}

fn render(
    icons: &icons::Manifest,
    fonts: &fonts::Manifest,
    themes: &ThemesManifest,
    conpty: &conpty::Manifest,
) -> Result<String> {
    let mut out = String::new();
    out.push_str("# Third-party notices\n\n");
    out.push_str(
        "<!-- Generated by `cargo xtask notices` (and `icons`, `fonts`, `conpty`) from \
         assets/icons/icons.toml, assets/fonts/fonts.toml, assets/themes/themes.toml and \
         assets/conpty/conpty.toml. Do not edit by hand. -->\n\n\
         OpenSesh is licensed under GPL-3.0-or-later (see `LICENSE`). It bundles the following \
         third-party assets and components, which keep their own licenses.\n\n## Icons\n\n",
    );
    for (source_id, used) in icons::used_icons(icons)? {
        let source = icons
            .sources
            .get(source_id)
            .with_context(|| format!("unknown icon source `{source_id}`"))?;
        let mut names: Vec<&str> = used.iter().map(|(_, upstream)| *upstream).collect();
        names.sort_unstable();
        names.dedup();
        let license = icons::license_copy(source_id);
        writeln!(out, "### {} {}\n", source.package, source.version)?;
        writeln!(out, "- Homepage: <{}>", source.homepage)?;
        writeln!(
            out,
            "- License: {}. Full text: [`{license}`]({license})",
            source.license
        )?;
        for file in &source.extra_notice_files {
            let copy = icons::notice_copy(source_id, file)
                .with_context(|| format!("invalid extra notice file `{file}`"))?;
            writeln!(out, "- Also read: [`{copy}`]({copy})")?;
        }
        if let Some(notice) = &source.notice {
            writeln!(out, "- Note: {}", notice.trim())?;
        }
        writeln!(
            out,
            "- Source: `https://registry.npmjs.org/{}` (tarball sha256 `{}`)",
            source.package, source.sha256
        )?;
        writeln!(out, "- Icons used: {}\n", code_list(&names))?;
    }

    out.push_str("## Fonts\n\n");
    for source in fonts.sources.values() {
        let license = format!("{}/{}", fonts::LICENSES_OUT, source.license_output);
        let files: Vec<&str> = source.files.values().map(String::as_str).collect();
        writeln!(out, "### {} {}\n", source.name, source.version)?;
        writeln!(out, "- Homepage: <{}>", source.homepage)?;
        writeln!(
            out,
            "- License: {}. Full text: [`{license}`]({license})",
            source.license
        )?;
        writeln!(
            out,
            "- Source: `{}` (sha256 `{}`)",
            source.url, source.sha256
        )?;
        writeln!(
            out,
            "- Files bundled (unmodified, in `crates/opensesh-app/fonts/`): {}\n",
            code_list(&files)
        )?;
    }

    out.push_str(
        "## Terminal color themes\n\n\
         OpenSesh Dark and OpenSesh Light are OpenSesh's own (GPL-3.0-or-later). The other \
         built-in themes are these upstream files, unmodified, in `assets/themes/upstream/`.\n\n",
    );
    for source in &themes.source {
        writeln!(out, "### {}\n", source.name)?;
        writeln!(
            out,
            "- Source: <{}> at commit `{}`",
            source.repository, source.commit
        )?;
        let texts: Vec<String> = source
            .license_files
            .iter()
            .map(|file| format!("[`{THEMES_DIR}/{file}`]({THEMES_DIR}/{file})"))
            .collect();
        writeln!(
            out,
            "- License: {}. Full text: {}",
            source.license,
            texts.join(", ")
        )?;
        let files: Vec<&str> = source.files.iter().map(String::as_str).collect();
        writeln!(out, "- Files bundled: {}\n", code_list(&files))?;
    }

    out.push_str("## Windows console host\n\n");
    let package = &conpty.package;
    let license = format!("{}/{}", conpty::LICENSE_DIR, package.license_output);
    let mut files: Vec<&str> = conpty
        .files
        .values()
        .map(|file| file.output.as_str())
        .collect();
    files.sort_unstable();
    writeln!(out, "### {} {}\n", package.id, package.version)?;
    writeln!(out, "- Homepage: <{}>", package.homepage)?;
    writeln!(
        out,
        "- License: {}. Full text: [`{license}`]({license})",
        package.license
    )?;
    writeln!(
        out,
        "- Source: `{}` (sha256 `{}`)",
        package.url, package.sha256
    )?;
    writeln!(
        out,
        "- Files bundled with the Windows build (unmodified, next to `opensesh-app.exe`): {}\n",
        code_list(&files)
    )?;
    // Exactly one trailing newline.
    let trimmed = out.trim_end().len();
    out.truncate(trimmed);
    out.push('\n');
    Ok(out)
}

fn code_list(items: &[&str]) -> String {
    items
        .iter()
        .map(|item| format!("`{item}`"))
        .collect::<Vec<_>>()
        .join(", ")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn repo_root() -> std::path::PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("..")
    }

    #[test]
    fn notices_cover_every_source_and_link_existing_licenses() {
        let root = repo_root();
        let icons = icons::load_manifest(&root).unwrap();
        let fonts = fonts::load_manifest(&root).unwrap();
        let conpty = conpty::load_manifest(&root).unwrap();
        let themes = load_themes(&root).unwrap();
        let text = render(&icons, &fonts, &themes, &conpty).unwrap();
        assert!(text.contains("## Icons\n"));
        assert!(text.contains("## Terminal color themes\n"));
        for source in &themes.source {
            assert!(text.contains(&format!("### {}", source.name)));
            for file in &source.license_files {
                assert!(root.join(THEMES_DIR).join(file).is_file(), "{file}");
            }
            for file in &source.files {
                assert!(
                    root.join(THEMES_DIR).join("upstream").join(file).is_file(),
                    "{file}"
                );
            }
        }
        assert!(text.contains("## Fonts\n"));
        assert!(text.contains("## Windows console host\n"));
        for (id, source) in &icons.sources {
            assert!(text.contains(&format!("### {} {}", source.package, source.version)));
            assert!(root.join(icons::license_copy(id)).is_file(), "{id}");
        }
        for source in fonts.sources.values() {
            assert!(text.contains(&format!("### {} {}", source.name, source.version)));
            assert!(
                root.join(fonts::LICENSES_OUT)
                    .join(&source.license_output)
                    .is_file()
            );
        }
        assert!(text.contains(&format!(
            "### {} {}",
            conpty.package.id, conpty.package.version
        )));
        assert!(
            root.join(conpty::LICENSE_DIR)
                .join(&conpty.package.license_output)
                .is_file()
        );
        assert!(text.ends_with("`OpenConsole.exe`, `conpty.dll`\n"));
    }

    /// `cargo xtask icons` / `fonts` must be re-run after editing a manifest.
    #[test]
    fn committed_notices_are_up_to_date() {
        let root = repo_root();
        let expected = render(
            &icons::load_manifest(&root).unwrap(),
            &fonts::load_manifest(&root).unwrap(),
            &load_themes(&root).unwrap(),
            &conpty::load_manifest(&root).unwrap(),
        )
        .unwrap();
        let committed = std::fs::read_to_string(root.join(NOTICES)).unwrap();
        assert_eq!(
            committed.replace("\r\n", "\n"),
            expected,
            "THIRD_PARTY_NOTICES.md is stale: run `cargo xtask notices`"
        );
    }
}
