//! Qt application setup and the event loop.

use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};

use anyhow::{Context, Result, bail};
use cxx_qt_lib::{QGuiApplication, QQmlApplicationEngine, QQuickStyle, QString, QUrl};
use opensesh_core::identity;

use crate::bridge::shim::ffi as shim;
use crate::bridge::theme::DEFAULT_UI_FONT;

/// Main window, compiled into the `cc.caixa.opensesh` QML module by `build.rs`.
pub const MAIN_QML: &str = "qrc:/qt/qml/cc/caixa/opensesh/qml/Main.qml";

/// Component gallery shown by the `--gallery` mode.
pub const GALLERY_QML: &str = "qrc:/qt/qml/cc/caixa/opensesh/qml/Gallery.qml";

/// Crash dialog shown by the `--crash-report` mode.
pub const CRASH_DIALOG_QML: &str = "qrc:/qt/qml/cc/caixa/opensesh/qml/CrashDialog.qml";

/// Placeholder application logo, generated by `cargo xtask icons`.
const WINDOW_ICON: &str = ":/qt/qml/cc/caixa/opensesh/data/icons/cc.caixa.OpenSesh.svg";

/// `QT_QPA_PLATFORM` value set on Windows when the user hasn't chosen a platform: Qt's Windows
/// plugin with its `altgr` option, so AltGr reaches the app as AltGr (`Qt::GroupSwitchModifier`)
/// instead of Ctrl+Alt. `opensesh-term` removes exactly this value from the environment of the
/// programs it starts, so Qt programs run in a terminal don't inherit it.
#[cfg(windows)]
const WINDOWS_ALTGR_PLATFORM: &std::ffi::CStr = c"windows:altgr";

/// Windows: sets `QT_QPA_PLATFORM` to `windows:altgr` unless the user set it (an empty value
/// counts as unset, as it does for Qt). Elsewhere it does nothing.
///
/// Must be the first thing `main` does, before any thread starts: see the SAFETY note.
///
/// `std::env::set_var` is not enough here. It calls `SetEnvironmentVariableW`, but Qt reads the
/// variable with `qgetenv`, which with MSVC is the C runtime's `getenv`, and the C runtime keeps
/// its own copy of the environment, taken at startup. The UCRT's `_putenv_s` updates both that
/// copy and the process environment (which `std::env` and child processes see).
pub fn enable_windows_altgr() {
    #[cfg(windows)]
    {
        unsafe extern "C" {
            /// UCRT: `errno_t _putenv_s(const char *varname, const char *value_string)`.
            fn _putenv_s(
                varname: *const std::ffi::c_char,
                value_string: *const std::ffi::c_char,
            ) -> std::ffi::c_int;
        }

        if std::env::var_os("QT_QPA_PLATFORM").is_none_or(|value| value.is_empty()) {
            // SAFETY: both pointers are NUL-terminated static strings. Changing the environment
            // is only unsound while another thread reads it through the C runtime (a pointer
            // returned by `getenv` can be freed by the update). This runs first in `main`: no
            // Rust or Qt thread exists yet (logging, the settings writer, the file watcher and
            // Qt's own threads all start later), and the only other threads a process can have
            // this early belong to the Windows loader, which doesn't use the C runtime's
            // environment. A failure (out of memory) only leaves AltGr as Ctrl+Alt; `run` logs
            // the value Qt ends up with.
            let _ =
                unsafe { _putenv_s(c"QT_QPA_PLATFORM".as_ptr(), WINDOWS_ALTGR_PLATFORM.as_ptr()) };
        }
    }
}

/// Creates the `QGuiApplication`, loads `qml_url` and runs the event loop until it exits.
/// `language` is the configured UI language, applied before the first frame.
///
/// Returns the exit code of the event loop.
///
/// # Errors
///
/// Whether some terminal profile makes the background translucent: only then does the window get
/// an alpha channel (it costs a little on some systems, and X11 without a compositor shows the
/// transparent parts black). Test runs never do.
fn wants_window_alpha() -> bool {
    if crate::bridge::app_info::is_test_run() {
        return false;
    }
    let Some(services) = crate::services::get() else {
        return false;
    };
    let dir = services
        .paths
        .config_dir()
        .join(opensesh_core::terminal::profile::PROFILES_DIR);
    // A few small files, read once before the window exists.
    let (profiles, _) = opensesh_core::terminal::profile::ProfileSet::load_dir(&dir);
    profiles.list().iter().any(|profile| {
        profile
            .terminal
            .background_opacity
            .is_some_and(|opacity| opacity < 0.999)
    })
}

/// Fails if Qt objects can't be created or the QML file fails to load.
pub fn run(qml_url: &str, language: &str) -> Result<i32> {
    crate::bridge::shim::install_qt_message_handler();
    // Our components are built on QtQuick.Templates; any stock control that slips in uses the
    // light, predictable Basic style. Must be set before QML is loaded.
    QQuickStyle::set_style(&QString::from("Basic"));

    let mut app = QGuiApplication::new();
    let mut app = app
        .as_mut()
        .context("could not create the QGuiApplication")?;
    app.as_mut()
        .set_application_name(&QString::from(identity::APP_NAME));
    app.as_mut()
        .set_application_version(&QString::from(identity::VERSION));
    app.as_mut()
        .set_organization_domain(&QString::from(identity::ORGANIZATION_DOMAIN));
    // Wayland app_id and the .desktop file the compositor associates with our windows.
    QGuiApplication::set_desktop_file_name(&QString::from(identity::APP_ID));
    if !shim::set_window_icon(&QString::from(WINDOW_ICON)) {
        tracing::warn!("could not load the window icon; is the Qt SVG image plugin installed?");
    }
    // Portable mode keeps everything under `<exe>/data` (PLAN §4.1); Qt would otherwise write
    // its shader pipeline cache to the per-user cache folder.
    if crate::services::get().is_some_and(|services| services.paths.is_portable()) {
        shim::disable_shader_disk_cache();
    }
    if wants_window_alpha() {
        shim::enable_window_alpha();
        crate::bridge::app_info::set_window_alpha(true);
        tracing::info!(
            "a terminal profile has a translucent background: the window gets an alpha channel"
        );
    }
    let fonts = shim::register_bundled_fonts();
    shim::set_application_font_family(&QString::from(DEFAULT_UI_FONT));
    // What Qt was asked for (on Windows usually `windows:altgr`, see `enable_windows_altgr`).
    let requested_platform = std::env::var_os("QT_QPA_PLATFORM").unwrap_or_default();
    tracing::info!(
        platform = %shim::platform_name(),
        qt_qpa_platform = %requested_platform.to_string_lossy(),
        app_id = identity::APP_ID,
        bundled_fonts = fonts,
        "Qt application created"
    );

    let mut engine = QQmlApplicationEngine::new();
    let mut engine = engine
        .as_mut()
        .context("could not create the QQmlApplicationEngine")?;

    shim::install_icon_provider(engine.as_mut());
    shim::set_translation_engine(engine.as_mut());
    shim::apply_translation(&QString::from(language));

    // Emitted synchronously from load() when the root object can't be created.
    let load_failed = Arc::new(AtomicBool::new(false));
    {
        let load_failed = Arc::clone(&load_failed);
        engine
            .as_mut()
            .on_object_creation_failed(move |_engine, url| {
                load_failed.store(true, Ordering::SeqCst);
                tracing::error!(url = %url, "QML root object creation failed");
            })
            .release();
    }
    engine.as_mut().load(&QUrl::from(qml_url));
    if load_failed.load(Ordering::SeqCst) {
        bail!("could not load {qml_url}; see the QML errors above");
    }

    Ok(app.exec())
}
